const levelNames = [
  "Novize",
  "Anfänger",
  "Lehrling",
  "Trainee",
  "Junior Lerner",
  "Suchender",
  "Neugieriger Entdecker",
  "Einsichtsvoller Anfänger",
  "Pfadfinder",
  "Aufstrebender Gelehrter",
  "Fleißiger Schüler",
  "Steter Aufsteiger",
  "Eifriger Lerner",
  "Fortgeschrittener Lerner",
  "Meister der Grundlagen",
  "Gewiefter Entdecker",
  "Schneller Lerner",
  "Könner",
  "Geschickter Lehrling",
  "Talentierter Schüler",
  "Kluger Gelehrter",
  "Heller Kopf",
  "Strategischer Denker",
  "Erfahrener Schüler",
  "Junior Analyst",
  "Schneller Denker",
  "Kritischer Denker",
  "Wissenssucher",
  "Innovativer Lerner",
  "Aufstrebender Experte",
  "Fortgeschrittener Gelehrter",
  "Dynamischer Problemlöser",
  "Energischer Entdecker",
  "Innovativer Gelehrter",
  "Unabhängiger Denker",
  "Analytischer Geist",
  "Kreativer Denker",
  "Aufmerksamer Gelehrter",
  "Fortgeschrittener Problemlöser",
  "Erfolgreicher Lerner",
  "Geschickter Denker",
  "Meisterlicher Lerner",
  "Erfahrener Entdecker",
  "Top Gelehrter",
  "Kritischer Analyst",
  "Meisterlicher Entdecker",
  "Elite Denker",
  "Lernspezialist",
  "Kognitive Stratege",
  "Senior Lerner",
  "Wissensarchitekt",
  "Wegbereiter",
  "Meistermind",
  "Innovativer Denker",
  "Lernchampion",
  "Visionärer Gelehrter",
  "Strategischer Experte",
  "Erfinderischer Gelehrter",
  "Meister der Konzepte",
  "Fortgeschrittener Entdecker",
  "Einsichtsvoller Experte",
  "Wissensbezwinger",
  "Elite-Gelehrter",
  "Lerninnovator",
  "Mentor der Köpfe",
  "Konzeptueller Meister",
  "Strategischer Innovator",
  "Besonnener Gelehrter",
  "Weiser Lerner",
  "Kognitiver Meister",
  "Vordenker",
  "Weiser Wissender",
  "Meisterstratege",
  "Elite Wissenssucher",
  "Innovativer Anführer",
  "Kognitives Genie",
  "Weiser des Lernens",
  "Lernmeistermind",
  "Nachdenklicher Architekt",
  "Meister des Wissens",
  "Großstratege",
  "Innovatives Genie",
  "Elite-Entdecker",
  "Visionärer Meister",
  "Lernwunderkind",
  "Gelehrter der Legenden",
  "Innovativer Visionär",
  "Kognitiver Großmeister",
  "Meister der Köpfe",
  "Weiser der Weisheit",
  "Oberster Wissenssucher",
  "Oberster Stratege",
  "Elite-Innovator",
  "Großmeister Gelehrter",
  "Legendärer Weiser",
  "Unendlicher Geist",
  "Kognitiver Titan",
  "Oberster Lernmeister",
  "Ultimativer Wissensbewahrer",
  "Meister aller Meister"
]

// Utility function to get level name based on player level
export const getLevelName = (level: number) => {
  return levelNames[Math.min(level, levelNames.length - 1)] || "Unknown Level";
};